### ISSUE TITLE
Custom characters display (Block character)

### ISSUE THREAD

**Issue by limbo666** [eeyrw/LcdEmulator#1]
Great approach. Nice Work.

It seems that the custom characters are supported, but for some reason the build-in bar and block character displays an "@" symbol.
 ![Screenshot_20240121-190321_LcmEmulator](https://github.com/eeyrw/LcdEmulator/assets/331155/b2e6a35f-2521-47e6-b7eb-c76075bee2f6)

You can easily reproduce it by just adding a block chacater from Misc. Tab on LCD Smartie Configuration.

**Comment by eeyrw** [comment]
It's caused by ASCII code pre-processing of my APP:
```java
        public Bitmap getCharBitmap(char ch) {

            // Type "char" in java is based on unicode.
            int charNum = ch & 0xff;

            // ' ' in ASCII is 32
            if (charNum >= 32 && charNum <= 127) {
                charNum -= 32;
            } else if (charNum >= 0 && charNum <= 7) {
                // 0~7 is used for custom char
                return mFontBitmapCustom[charNum];
            } else {
                charNum = 32;  // Finally got '@'
            }

            return mFontBitmapMain[charNum];

        }
```
My code does not process ASCII char out of 32~127 which is not in my font. and I found the fact that block(█) is 253? I just wonder block(█) is the built-in visible character of HD44780? I just place block char on Char(127) and it works in LCD Smartie 5.4.

I can remap the  block(█) to Char(127) for solving the problem. But, the char usage of LCD Smartie is still mysterious to me when implementing the driver DLL.

**Comment by limbo666** [comment]
Great work! Thank you
![Screenshot_20240122-210635_LcmEmulator](https://github.com/eeyrw/LcdEmulator/assets/331155/c1405a6a-1512-464b-a0eb-5dda72191307)
